parameters:
#    onscreen_screen.example.class: Onscreen\ScreenBundle\Example

services:
#    onscreen_screen.example:
#        class: %onscreen_screen.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
